version: "3"
services:
	manager:
		build: .
			
		environment:
			CSV_FILENAME="data.csv"
      POSTGRES_USER="root"
      POSTGRES_PASSWORD="password"
      POSTGRES_DB="database"
    depends_on:
      -db


	db:
		image: "postgres"
    ports:
      -"5432:5432"
    environment:
      CSV_FILENAME="data.csv"
      POSTGRES_USER="root"
      POSTGRES_PASSWORD="password"
      POSTGRES_DB="database"