FROM python:3.8

RUN pip install psycopg2

ADD . /package

ENV CSV_FILENAME=data.csv
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=database

RUN wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -P /
RUN chmod +x /wait-for-it.sh
ENTRYPOINT ["/wait-for-it.sh", "db:5432", "--"]

EXPOSE 5432

CMD ["python", "-m", "package"]